### ISSUE TITLE
Reset Button Styling on Mobile

### ISSUE THREAD

**Issue by jordon-young** [jordon-young/fem-tip-calculator#1]
The reset button border radius and padding does not match the design on Chrome iOS and Safari iOS. Everything looks normal on all breakpoints on desktop Chrome, Firefox, and Edge.

![image](https://user-images.githubusercontent.com/64931019/156673930-3d85136b-e491-40dd-833b-e4bd1d34c296.png)

![image](https://user-images.githubusercontent.com/64931019/156673940-d7f6d69e-b13d-4eaa-94f3-28c7ea24e34a.png)

**Comment by jordon-young** [comment]
### The issue: iOS Default Styles

```css
input[type=reset] {
  -webkit-appearance: button;
}
```
The iOS browser defaults for padding and border-radius were overriding my styles. 
___

### Added to _resets.scss

```css
input[type=reset] {
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;
}
```
